[build]
publish = "storybook-static"
command = "pnpm build-storybook"

[build.environment]
NODE_VERSION = "22"

[[rewrite]]
from = "/sb-preview/*"
to = "/sb-manager/*"
status = 200

# [[headers]]
# for = "/manifest.webmanifest"

# [headers.values]
# Content-Type = "application/manifest+json"
